### ISSUE TITLE
Can't catch when a speed up transaction is confirmed

### ISSUE THREAD

**Issue by duyphanz** [icon-project/Nexus#626]
https://user-images.githubusercontent.com/13731780/176178573-e5bf9f90-b65d-4acd-b8ae-0241f3c8fdde.mp4

Step to reproduce: speed up a transaction from Metamask

- Actual result: dApp can't catch when the tx is confirmed

ref: https://github.com/ChainSafe/web3.js/issues/3585

**CHECKLIST**:

- [x] Fix for MetaMask
- [ ] Check this issue with Hana https://github.com/icon-project/Nexus/issues/626#issuecomment-1172431242

**Comment by CyrusVorwald-ICON** [comment]
It's not worth doing the research at this time. Can we close this issue?

**Comment by duyphanz** [comment]
I'll close this issue, we can open a new issue for Hana with more details if necessary
