### ISSUE TITLE
Add a banner to the nexus site.

### ISSUE THREAD

**Issue by FezBox** [icon-project/Nexus#650]
Add a banner like this on the nexus site 
![image](https://user-images.githubusercontent.com/107530591/179676937-1b03c095-bd86-41f2-acd3-5b8527819a87.png)

add to this part of the site 
![image](https://user-images.githubusercontent.com/107530591/179677053-b64f5c2d-6097-4551-aecd-43987db4c8b8.png)

Text to say:
Nexus is in beta while ICON Bridge is currently being audited. Please ensure you have read the [terms of use.](url)

Please have the terms of use hyperlinked so if clicked on it brings up the terms of use window.
![image](https://user-images.githubusercontent.com/107530591/179678865-b7497473-7d6d-4a6d-86d9-7bdf0a14fa2e.png)

Use the same blue colour as the connect button.

**Comment by duyphanz** [comment]
Deployed to https://staging.nexusportal.io/transfer

**Comment by FezBox** [comment]
Hey @duyphanz looks good! could we make the following changes, please

![image](https://user-images.githubusercontent.com/107530591/179887752-05fd552c-12c1-4d2f-b0de-be45187cece8.png)


- Center the message 
- Cover the message in blue like the connect wallet button

**Comment by duyphanz** [comment]
Hi @FezBox, I'd like to clarify a bit:

- The text color is still white, and there is a blue background to make the text stand out?
- On a small screen (like my laptop), centering the text will make it overlap the navigation section. So, I decided to make it center between the navigation section and connect wallet button as current. In this case, how about leaving the text center and under the header?

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/13731780/179889929-72027e93-4680-4094-b9cc-a1ef482aa7e7.png">
