### ISSUE TITLE
Curve takes a long time to load

### ISSUE THREAD

**Issue by CyrusVorwald-ICON** [icon-project/Nexus#663]
Clicking either ICON or BSC in Networks opens a popup that says "Curve" that takes approximately 5 seconds to load. I'm not sure what is going on in the backend that this is taking so long to load, but from the data that pops up, it seems this should be near instantaneous.

**Comment by CyrusVorwald-ICON** [comment]
Is there any update on this?

**Comment by sanglt1902** [comment]
It only happened on testnet because we deploy different regions between the backend and database, so that the request time will be long. It doesn't happen with the production

**Comment by CyrusVorwald-ICON** [comment]
@sanglt1902 thanks.
