### ISSUE TITLE
Mobile-friendly tables

### ISSUE THREAD

**Issue by CyrusVorwald-ICON** [icon-project/Nexus#665]
The text in tables currently collapses on mobile in a non readable way. This may happen on tablets as well.

<img width="554" alt="image" src="https://user-images.githubusercontent.com/90732384/181782567-78289965-a60f-4e37-9c2e-4758c2479685.png">

Additionally, the box around the transaction status does not fit the text.
<img width="563" alt="image" src="https://user-images.githubusercontent.com/90732384/181782646-25f41453-c9cc-4044-8e85-b813e9cb9495.png">

There's a few ways to go about having tables be mobile-friendly (see https://lightit.io/blog/responsivetables/ for some examples). @RiseBlock I leave this up to you on how to best resolve this. We can discuss further on which way to go if you want more input.

**Comment by duyphanz** [comment]
I found this issue occurs in safari or iOS's browser. Now, I fixed it by making the table scrollable horizontally. Please have a check again, and let me know if we need any further adjustment

**Comment by CyrusVorwald-ICON** [comment]
Looks good. Closing this
