### ISSUE TITLE
Change "Binance Smart Chain" to "BNB Smart Chain"

### ISSUE THREAD

**Issue by rhizome-labs** [icon-project/Nexus#666]
Binance rebranded Binance Smart Chain to BNB Smart Chain earlier this year, so the old name should be updated on frontend.

Reference: https://www.binance.com/en/blog/ecosystem/introducing-bnb-chain-the-evolution-of-binance-smart-chain-421499824684903436

```
BNB Chain is comprised of:

* BNB Beacon Chain (previously Binance Chain) - BNB Chain Governance (Staking, Voting)
* BNB Smart Chain (BSC) (Previously Binance Smart Chain) - EVM compatible, consensus layers, and with hubs to multi-chains
```

**Comment by duyphanz** [comment]
Hi @CyrusVorwald-ICON, I'd hear your thoughts about this
