### ISSUE TITLE
Words cut off on smaller browser windows

### ISSUE THREAD

**Issue by CyrusVorwald-ICON** [icon-project/Nexus#672]
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/90732384/183789710-9a38bb58-6a86-4f34-98c0-7efc28ed1ace.png">

"Chain" should be on its own line in this instance.

**Comment by duyphanz** [comment]
This issue has been fixed, please try to refresh the page if you're still experiencing due to cache
<img width="468" alt="image" src="https://user-images.githubusercontent.com/13731780/183796749-a86b97c3-97c5-47e7-9f93-a1b99d99610d.png">
