### ISSUE TITLE
"invalid hexlify value" error

### ISSUE THREAD

**Issue by tjhunt1** [icon-project/Nexus#675]
**Describe the bug**
Trying to transfer 0.01 BNB from Binance Smart Chain to ICON

**To Reproduce**
1. Log into your Metamask wallet and choose Binance Smart Chain
2. Go to [Transfer](https://testnet.nexusportal.io/transfer)
3. Click on send BNB to ICON
4. Transfer 0.01 BNB to ICON address and click "Transfer"
5. Click "Approve"
6. See error

**Expected behavior**
About an hour ago, I was able to do this process without an error. This time however, I can no longer transfer my BNB from Binance Smart Chain to ICON.

**Screenshots**
<img width="718" alt="Screen Shot 2022-08-10 at 1 36 31 PM" src="https://user-images.githubusercontent.com/98855020/183990713-ab455f34-a00b-468a-837d-fcea20dbbe6f.png">

**Comment by tjhunt1** [comment]
The same issue occurred when trying to unwrap 10 ICX from Binance Smart Chain to ICON

<img width="622" alt="Screen Shot 2022-08-10 at 1 38 35 PM" src="https://user-images.githubusercontent.com/98855020/183991091-f0647dc7-bd1a-49f4-a48d-4f84d7bfa40c.png">

**Comment by duyphanz** [comment]
I've tested this case and cannot reproduce it. Let's monitor this issue.

**Comment by tjhunt1** [comment]
hmm, I'm still running into the same error @duyphanz

**Comment by tjhunt1** [comment]
weird now it works for me again 🤔

**Comment by CyrusVorwald-ICON** [comment]
Closing this as stale
