### ISSUE TITLE
"Network" page not being properly updated

### ISSUE THREAD

**Issue by tjhunt1** [icon-project/Nexus#679]
**Describe the bug**
"Network" page states that there is 0 Volume (24hr) for both ICON and BNB Smart Chain even though I have sent multiple transactions the past few hours.

**To Reproduce**
[Network page](https://testnet.nexusportal.io/network)

**Expected behavior**
There should be some X amount of Volume (24hr) populated in this page.

**Screenshots**

<img width="1423" alt="Screen Shot 2022-08-10 at 2 07 23 PM" src="https://user-images.githubusercontent.com/98855020/183997154-ae590ec7-9ff4-4a74-a1a4-42de3d25ceb8.png">

**Additional context**
How is the Volume being tracked. $$$ value? Native coin value (ICX for ICON, BNB for BSC)?

**Comment by sanglt1902** [comment]
it's total volume of all tokens(including native and non-native coin) were transferred via nexus within 24h

**Comment by sanglt1902** [comment]
fixed
