### ISSUE TITLE
"History" tab UX

### ISSUE THREAD

**Issue by tjhunt1** [icon-project/Nexus#680]
**Is your feature request related to a problem? Please describe.**
It's not intuitive to me that you can click on a specific transaction on the "History" tab.

**Describe the solution you'd like**
I would like for there to be a "View" button to the right of the "Status" column that pulls up your "Transfer details"

**Describe alternatives you've considered**
Change the pointer cursor to the hand (which means clickable)

**Additional context**
**Solution**
<img width="1246" alt="Screen Shot 2022-08-10 at 2 14 20 PM" src="https://user-images.githubusercontent.com/98855020/184000670-ca4b1451-56bc-44c9-9fb0-c9c1089c2f79.png">

**Alternative Solution**
Change pointer from this
![image](https://user-images.githubusercontent.com/98855020/184000938-28af93f6-bfc1-42ff-b1f2-7c762e5be6db.png)

To this
![image](https://user-images.githubusercontent.com/98855020/184001230-5a24f169-2d8c-47a3-a069-41cae97e4e02.png)

**Comment by CyrusVorwald** [comment]
Let's go with the alternative solution @RiseBlock @duyphanz
