### ISSUE TITLE
Fee and asset received are NaN

### ISSUE THREAD

**Issue by CyrusVorwald-ICON** [icon-project/Nexus#696]
**Describe the bug**
Can't receive funds due to NaN fee

**To Reproduce**
1. Use ICON wallet
2. Attempt to transfer ICX to BSC

**Expected behavior**
Fee should display a number instead of NaN and the destination wallet should receive the transferred asset.

**Screenshots**
<img width="500" alt="image" src="https://user-images.githubusercontent.com/90732384/185228703-bbda07b8-b508-4148-9c91-6123a15ceb8d.png">

**Desktop (please complete the following information):**
chrome

**Comment by pragyanshrestha-ibriz** [comment]
NaN (Not a Number) is a value output by javascript code.
@CyrusVorwald-ICON  This is might on Nexus's end. The fee shown also seems inconsistent as the earlier example the fee was showing up.

**Comment by CyrusVorwald-ICON** [comment]
Yeah I think the values may have just not loaded at the time. Haven't been able to replicate it.

**Comment by CyrusVorwald-ICON** [comment]
Closing since this is stale and not replicated.
