### ISSUE TITLE
Transfers stuck without showing up in history

### ISSUE THREAD

**Issue by CyrusVorwald-ICON** [icon-project/Nexus#697]
**Describe the bug**
Transactions appears to be going through, the asset is removed from the origin wallet/address, but the asset doesn't arrive in the destination address/wallet. Same issue  in both directions: ICX from ICON to BNB chain and BNB from BNB chain to ICON chain.

**To Reproduce**
Send ICX from ICON to BNB chain or BNB from BNB chain to ICON chain

**Expected behavior**
Transfer successfully ends up in destination wallet

**Screenshots**
Two instances of the same issue
![image](https://user-images.githubusercontent.com/90732384/185235988-99de5662-c77f-4751-8a0f-b21d23d5bea1.png)
![image](https://user-images.githubusercontent.com/90732384/185236038-366d40fd-5a7b-469e-9046-885091315ce9.png)

**Additional context**
This issue was reported by 2 users over Discord. It may be an issue with the ICON Bridge instead of Nexus

Wallet addresses to check:
ICX: hx35a5e8565b07923caef79e99c8656bfd299fb8d5
BNB: 0x3B04344662521Bf01371E49F598FA2C6AE1ffC18

**Comment by pragyanshrestha-ibriz** [comment]
Nexus deployment process is not complete yet. It should work as expected once the deployment is complete.
