### ISSUE TITLE
Nexus portal (staging) does not show balance in ICON side contracts

### ISSUE THREAD

**Issue by bbist** [icon-project/Nexus#698]
**Describe the bug**
Nexus portal does not show balance of BUSD token (`btp-0x38.bsc-BUSD`) on ICON even though hana shows that balance.

**To Reproduce**
1. Transfer BUSD from BSC to ICON wallet.
2. Go to nexus portal and try to transfer BUSD from ICON wallet back to BSC.

**Expected behavior**
You should be able to transfer balance back from ICON to BSC.

**Screenshots**
![image](https://user-images.githubusercontent.com/76272791/186355154-7ca2194b-4a39-49ca-adae-771f5fa01d82.png)

**Comment by CyrusVorwald-ICON** [comment]
Where is the code associated with this fix?
