### ISSUE TITLE
Transfer approval popup is too visually similar to transfer submitted popup

### ISSUE THREAD

**Issue by CyrusVorwald-ICON** [icon-project/Nexus#705]
**Is your feature request related to a problem? Please describe.**
These two popups look too similar.
<img width="478" alt="image" src="https://user-images.githubusercontent.com/90732384/187308572-72456c98-6fb4-44bf-ae46-85c1ea30b0b4.png">

<img width="492" alt="image" src="https://user-images.githubusercontent.com/90732384/187308603-15b0412c-f775-4889-81c0-1c41a912feb2.png">

**Describe the solution you'd like**
Use a different icon than a green checkmark in this instance

<img width="478" alt="image" src="https://user-images.githubusercontent.com/90732384/187308497-43e79b7b-8909-45eb-aa16-df46d378933a.png">

**Describe alternatives you've considered**
I have not considered any other alternatives.

**Comment by duyphanz** [comment]
Do you have any suggestions about the icon in particular? @CyrusVorwald-ICON  Or I'll pick one from https://www.flaticon.com/search?word=transfer as a replacement

**Comment by RiseBlock** [comment]
@duyphanz let's remain the icon while having an alternative color.
If it's been approved, the icon color should be **yellow**.
It it's been transferred, the icon color should be **green**.

**Comment by duyphanz** [comment]
deployed to https://staging.nexusportal.io/
